// State artwork table: one 360x360 palette-indexed illustration per screen.
// PNG sources live in assets/states/ (generated by tools/gen_state_art.py,
// prepped by tools/prep_state_art.py, converted by tools/build_face_bitmap.mjs).
#pragma once
#include <stdint.h>

#include "art_cutting.h"
#include "art_done.h"
#include "art_err_flame.h"
#include "art_err_laser.h"
#include "art_err_lid.h"
#include "art_err_limit.h"
#include "art_err_moved.h"
#include "art_err_wifi.h"
#include "art_error.h"
#include "art_framing.h"
#include "art_idle.h"
#include "art_paused.h"
#include "art_ready.h"
#include "art_searching.h"
#include "art_sleeping.h"

namespace ui {

enum Screen : uint8_t {
  SCR_SEARCH = 0, // wifi down / laser not found / link lost
  SCR_IDLE,
  SCR_SLEEP,
  SCR_READY,
  SCR_FRAME,
  SCR_CUT,
  SCR_PAUSE,
  SCR_DONE,
  SCR_ERROR, // generic warning triangle (wifi-setup mode)
  SCR_ERR_FLAME,
  SCR_ERR_MOVED,
  SCR_ERR_LID,
  SCR_ERR_LIMIT,
  SCR_ERR_WIFI,
  SCR_ERR_LASER,
  SCR_COUNT
};

struct StateArt {
  const uint16_t *pal;
  const uint8_t *px;
};

static const StateArt STATE_ART[SCR_COUNT] = {
    {art_searching::PALETTE, art_searching::PIXELS},
    {art_idle::PALETTE, art_idle::PIXELS},
    {art_sleeping::PALETTE, art_sleeping::PIXELS},
    {art_ready::PALETTE, art_ready::PIXELS},
    {art_framing::PALETTE, art_framing::PIXELS},
    {art_cutting::PALETTE, art_cutting::PIXELS},
    {art_paused::PALETTE, art_paused::PIXELS},
    {art_done::PALETTE, art_done::PIXELS},
    {art_error::PALETTE, art_error::PIXELS},
    {art_err_flame::PALETTE, art_err_flame::PIXELS},
    {art_err_moved::PALETTE, art_err_moved::PIXELS},
    {art_err_lid::PALETTE, art_err_lid::PIXELS},
    {art_err_limit::PALETTE, art_err_limit::PIXELS},
    {art_err_wifi::PALETTE, art_err_wifi::PIXELS},
    {art_err_laser::PALETTE, art_err_laser::PIXELS},
};

} // namespace ui
