#!/usr/bin/env node
// Convert the display-sized PNG into a compact, dependency-free firmware
// header: an RGB565 palette plus one byte per pixel. ImageMagick is used only
// to decode the PNG; the committed header is what the ESP32 build consumes.

import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { basename } from "node:path";

const [input, output, namespaceName = "olmec_bitmap"] = process.argv.slice(2);
if (!input || !output) {
  console.error("usage: node build_face_bitmap.mjs input.png output.h [namespace]");
  process.exit(2);
}
if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(namespaceName))
  throw new Error(`invalid C++ namespace: ${namespaceName}`);

const W = 360;
const H = 360;
const decodeArgs = [input, "-depth", "8", "rgb:-"];
let decoded = spawnSync("magick", decodeArgs, { encoding: null, maxBuffer: W * H * 4 });
if (decoded.error?.code === "ENOENT")
  decoded = spawnSync("convert", decodeArgs, { encoding: null, maxBuffer: W * H * 4 });
if (decoded.status !== 0) {
  process.stderr.write(decoded.stderr || Buffer.from("ImageMagick failed\n"));
  process.exit(decoded.status || 1);
}
const rgb = decoded.stdout;
if (rgb.length !== W * H * 3) {
  throw new Error(`expected ${W * H * 3} decoded bytes, got ${rgb.length}`);
}

const palette = [];
const paletteIndex = new Map();
const pixels = new Uint8Array(W * H);
for (let i = 0; i < pixels.length; i++) {
  const r = rgb[i * 3];
  const g = rgb[i * 3 + 1];
  const b = rgb[i * 3 + 2];
  const c = ((r & 0xf8) << 8) | ((g & 0xfc) << 3) | (b >> 3);
  let pi = paletteIndex.get(c);
  if (pi === undefined) {
    pi = palette.length;
    if (pi >= 256) throw new Error("RGB565 palette exceeded 256 colors");
    paletteIndex.set(c, pi);
    palette.push(c);
  }
  pixels[i] = pi;
}

const hex4 = (n) => `0x${n.toString(16).padStart(4, "0")}`;
const hex2 = (n) => `0x${n.toString(16).padStart(2, "0")}`;
const rows = [];
for (let y = 0; y < H; y++) {
  const line = [];
  for (let x = 0; x < W; x++) line.push(hex2(pixels[y * W + x]));
  rows.push(`  ${line.join(", ")},`);
}

const header = `// Generated by tools/build_face_bitmap.mjs from ${basename(input)}.
// ${W}x${H}, ${palette.length}-color RGB565 palette, ${pixels.length} byte indices.
// Regenerate; do not hand-edit.
#pragma once
#include <stdint.h>

namespace ${namespaceName} {
constexpr int WIDTH = ${W};
constexpr int HEIGHT = ${H};
constexpr int PALETTE_SIZE = ${palette.length};

static const uint16_t PALETTE[PALETTE_SIZE] = {
  ${palette.map(hex4).join(", ")}
};

static const uint8_t PIXELS[WIDTH * HEIGHT] = {
${rows.join("\n")}
};
} // namespace ${namespaceName}
`;

writeFileSync(output, header);
console.log(`${output}: ${W}x${H}, ${palette.length} RGB565 colors, ${pixels.length + palette.length * 2} bytes`);
